services:
  - type: web
    name: mma-gym-management
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NPM_VERSION  
        value: latest
    healthCheckPath: /
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1